exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('games').truncate()
    .then(function () {
      return Promise.all([
        knex('games').insert({owner_id: 2, is_custom_venue: 1,
          game_title: "Game 2",
          opponent: "The other team 1",
          public: 1,
          game_time: 1231231231221231233,
          time_created: 0, 
          description: "",
          is_training: false, 
          game_type: "Game",
          lat: 0, lon: 0, }),
        knex('games').insert({owner_id: 2, is_custom_venue: 1,
          game_title: "Game 2",
          opponent: "The other team 2",
          public: 1,
          game_time: 1231231231221231233,
          time_created: 0, 
          description: "",
          is_training: false, 
          game_type: "Game",
          lat: 0, lon: 0, }),
        knex('games').insert({owner_id: 2, is_custom_venue: 1,
          game_title: "Game 3",
          opponent: "The other team 3",
          public: 1,
          game_time: 1231231231221231233,
          time_created: 0, 
          description: "",
          is_training: false, 
          game_type: "Game",
          lat: 0, lon: 0, }),
        knex('games').insert({owner_id: 2, is_custom_venue: 1,
          game_title: "Game 4",
          opponent: "The other team 4",
          public: 1,
          game_time: 1231231231221231233,
          time_created: 0, 
          description: "",
          is_training: false, 
          game_type: "Game",
          lat: 0, lon: 0, }),
        knex('games').insert({owner_id: 2, is_custom_venue: 1,
          game_title: "Game 5",
          opponent: "The other team 5",
          public: 1,
          game_time: 1231231231221231233,
          time_created: 0, 
          description: "",
          is_training: false, 
          game_type: "Game",
          is_team_game: true,
          team_id: 2,
          lat: 0, lon: 0, }),
        knex('games').insert({owner_id: 2, is_custom_venue: 1,
          game_title: "Training 1",
          opponent: "The other team 1",
          public: 1,
          game_time: 1231231231221231233,
          time_created: 0, 
          description: "",
          is_training: true, 
          game_type: "Training",
          is_team_game: true,
          team_id: 2,
          lat: 0, lon: 0, }),
      ]);
    });
}
